// Cell Biology Question Bank — Group 3
// MCQ shape: { q, options:[a,b,c,d], correctIndex, explain, difficulty }
// SAQ shape: { q, a, difficulty }
// difficulty: 'easy' | 'medium' | 'hard'

const SET1 = {
  mcq: [
    { q:"What is the specific thickness range of the plasma membrane as described in the Fluid-Mosaic model?",
      options:["1–5 nm","0.1 mm","7–10 nm","10–15 nm"], correctIndex:2, difficulty:"easy",
      explain:"The fluid-mosaic model places the membrane's thickness at 7–10 nm — far too thin to see without an electron microscope." },
    { q:'In the Fluid-Mosaic model, the "Mosaic" refers specifically to the arrangement of:',
      options:["Lipids behaving like a liquid","Proteins arranged like tiles","Cellulose fibers in the wall","Water molecules in a bilayer"], correctIndex:1, difficulty:"medium",
      explain:'"Mosaic" describes the scattered, tile-like arrangement of proteins among the lipids — the lipids are the "fluid" part of the name.' },
    { q:"If mung bean seeds are kept in a concentrated solution after soaking in water for 12 hours, they will:",
      options:["Swell further","Remain unchanged","Shrink due to water loss","Burst instantly"], correctIndex:2, difficulty:"medium",
      explain:"A concentrated (hypertonic) outside solution pulls water out of the swollen seed by osmosis, so it shrinks instead of swelling further." },
    { q:"Which type of solution has a lower solute concentration (more water) than the inside of the cell?",
      options:["Isotonic solution","Hypertonic solution","Hypotonic solution","Saturated solution"], correctIndex:2, difficulty:"easy",
      explain:"A solution with more water relative to the cell is hypotonic — water will tend to move into the cell." },
    { q:"The lipid bilayer of the cell membrane consists of molecules with:",
      options:["Water-attracting heads pointing inward","Water-repelling tails pointing outward","Water-attracting heads pointing outward","No attraction to water at all"], correctIndex:2, difficulty:"medium",
      explain:"Hydrophilic heads face outward toward the watery environment on both sides of the membrane; the hydrophobic tails point inward, away from water." },
    { q:"Which carbohydrate provides structural strength and rigidity to the plant cell wall?",
      options:["Glucose","Starch","Cellulose","Chitin"], correctIndex:2, difficulty:"easy",
      explain:"Cellulose's long fibers give the wall tensile strength — starch is a storage molecule, and chitin belongs to fungi/insects, not plants." },
    { q:"Plasmolysis in a plant cell is specifically defined as:",
      options:["The swelling of the cell in plain water","Shrinkage of content away from the cell wall","The breakdown of the cell's nucleus","The absorption of minerals from the soil"], correctIndex:1, difficulty:"medium",
      explain:"Plasmolysis is the shrinking of the cell's contents away from the wall — the rigid wall itself stays put." },
    { q:"The movement of water across a selectively permeable membrane is called:",
      options:["Diffusion","Active Transport","Osmosis","Endocytosis"], correctIndex:2, difficulty:"easy",
      explain:"Osmosis is the specific term for water diffusing across a selectively permeable membrane." },
    { q:"Which of these is a defining characteristic of the plant cell wall?",
      options:["It is selectively permeable and living","It is rigid, non-living, and permeable","It is thin, flexible, and made of lipids","It is found in both animal and plant cells"], correctIndex:1, difficulty:"medium",
      explain:"The cell wall is rigid and made of non-living cellulose, but it still lets water and minerals pass through freely — that's the \"permeable\" part." },
    { q:"Singer and Nicolson proposed the currently accepted Fluid-Mosaic model in the year:",
      options:["1665","1839","1972","1855"], correctIndex:2, difficulty:"easy",
      explain:"Singer and Nicolson published the fluid-mosaic model in 1972. (1665 is when Robert Hooke first observed cells in cork.)" }
  ],
  saq: [
    { q:"Define diffusion as described in the textbook.", a:"Diffusion is the net movement of particles from a higher to a lower concentration without requiring a membrane.", difficulty:"easy" },
    { q:"What is the mathematical value of 1 nanometre (nm) in millimetres (mm)?", a:"1 nanometre equals 0.000001 mm.", difficulty:"medium" },
    { q:'Why is the cell membrane described as "fluid"?', a:"It is fluid because the lipid and protein molecules can move sideways, flip, and rotate within the membrane.", difficulty:"medium" },
    { q:'Which specific part of the cell membrane acts as a "gatekeeper"?', a:"The various types of proteins embedded in the membrane act as gatekeepers for substances.", difficulty:"easy" },
    { q:"What happens to the weight of a potato piece when placed in a 20% salt solution?", a:"The weight of the potato piece decreases because water moves out of the cells by osmosis.", difficulty:"medium" },
    { q:"Name the condition where there is no net movement of water into or out of the cell.", a:"This condition occurs when a cell is placed in an isotonic solution.", difficulty:"easy" },
    { q:"Identify the process by which plant roots absorb water from the soil.", a:"Plant roots absorb water through the process of osmosis.", difficulty:"easy" },
    { q:"Why do animal cells shrink entirely in concentrated solutions unlike plant cells?", a:"Animal cells shrink entirely because they lack a rigid cell wall to maintain their outer shape.", difficulty:"hard" },
    { q:"What is the primary function of the cell wall in stationary plants?", a:"The cell wall provides structural rigidity to withstand environmental stresses like wind and rain.", difficulty:"easy" },
    { q:"Identify the water-repelling part of the lipid molecule in the plasma membrane.", a:'The "tails" of the lipid molecules are water-repelling, or hydrophobic.', difficulty:"easy" },
    { q:'What is meant by the term "concentration gradient"?', a:"It is the difference in the concentration of particles between two areas.", difficulty:"easy" },
    { q:"What is the immediate effect of a hypotonic solution on an animal cell?", a:"The animal cell will gain water, swell, and may eventually burst.", difficulty:"medium" },
    { q:"Which organic molecules are the primary components of the plasma membrane?", a:"The plasma membrane is primarily composed of lipids (fats) and proteins.", difficulty:"easy" },
    { q:'Why is the cell wall described as "permeable"?', a:"It is permeable because it allows water and dissolved minerals to pass through it freely.", difficulty:"medium" },
    { q:"What structure defines the individuality of a cell by separating its contents from the environment?", a:"The cell membrane (plasma membrane) defines the individuality of a cell.", difficulty:"medium" },
    { q:"Which process is responsible for oxygen entering the cell during respiration?", a:"Oxygen enters the cell through the process of diffusion.", difficulty:"easy" },
    { q:"What is the state of a plant cell when its vacuole is full of water and pushing against the wall?", a:'The cell is in a "turgid" state.', difficulty:"easy" },
    { q:"Name the stain used when preparing a temporary slide of Rhoeo leaf peel.", a:"Safranin is the stain used to observe these plant cells.", difficulty:"easy" },
    { q:'Why is the cell membrane called "selectively permeable"?', a:"It is called so because it allows only selected substances to pass while blocking others.", difficulty:"medium" },
    { q:"What happens to the osmotic ability of a Rhoeo leaf cell if it is boiled?", a:"Boiling kills the cell and its membrane, which prevents osmosis and plasmolysis from occurring.", difficulty:"hard" }
  ]
};

const SET2 = {
  mcq: [
    { q:"What is the primary function of the mirror in a light microscope?",
      options:["To magnify the specimen image","To reflect and focus sunlight onto the specimen","To hold the glass slide in place","To change the objective lens power"], correctIndex:1, difficulty:"easy",
      explain:"Before built-in lamps, microscopes used a mirror to catch ambient or sunlight and direct it up through the specimen." },
    { q:'The "Near Point" of the human eye, the closest distance for comfortable vision, is:',
      options:["10 cm","25 cm","0.1 mm","1 metre"], correctIndex:1, difficulty:"easy",
      explain:"25 cm is the standard near point used in optics for the unaided human eye." },
    { q:"Which process allows an Amoeba to engulf food due to its flexible membrane?",
      options:["Plasmolysis","Diffusion","Endocytosis","Exosmosis"], correctIndex:2, difficulty:"medium",
      explain:"Endocytosis is the membrane folding around and engulfing particles — exactly how an Amoeba feeds." },
    { q:"While plant cell walls are made of cellulose, fungal cell walls are composed of:",
      options:["Peptidoglycan","Lipids","Chitin","Proteins"], correctIndex:2, difficulty:"easy",
      explain:"Chitin — the same tough polymer in insect exoskeletons — makes up fungal cell walls instead of cellulose." },
    { q:"A microscope has a 10X eyepiece and a 40X objective lens. What is the total magnification?",
      options:["50X","400X","4X","100X"], correctIndex:1, difficulty:"medium",
      explain:"Total magnification is eyepiece × objective: 10 × 40 = 400X." },
    { q:'In the Fluid-Mosaic model, which molecules form the continuous "fluid" bilayer?',
      options:["Proteins","Phospholipids","Cellulose","ATP"], correctIndex:1, difficulty:"medium",
      explain:"Phospholipids form the continuous bilayer sheet; proteins are scattered within it, not the bilayer itself." },
    { q:"What is the effect of cold temperatures on the lipid bilayer of the cell membrane?",
      options:["Molecules move faster","The membrane becomes more fluid","Lipids pack together and the membrane becomes rigid","The membrane dissolves"], correctIndex:2, difficulty:"hard",
      explain:"Cold causes the lipid tails to pack tightly together, making the membrane stiffer rather than fluid." },
    { q:"In the potato cup experiment, why is Cup D (boiled potato) unable to gather water?",
      options:["It lacks sugar/salt","Boiling destroys the selectively permeable membrane","The potato is too hard","Boiling increases the concentration gradient"], correctIndex:1, difficulty:"medium",
      explain:"Boiling denatures the membrane's proteins, so it loses its selective permeability and can no longer draw in water." },
    { q:"The cell wall of bacteria is chemically composed of:",
      options:["Cellulose","Chitin","Peptidoglycan","Starch"], correctIndex:2, difficulty:"easy",
      explain:"Peptidoglycan is the characteristic structural molecule of bacterial cell walls." },
    { q:"Water moves from a dilute solution to a concentrated solution across a membrane during:",
      options:["Active transport","Diffusion","Osmosis","Evaporation"], correctIndex:2, difficulty:"easy",
      explain:"Osmosis moves water toward the side with more solute, evening out the concentration on both sides." }
  ],
  saq: [
    { q:"How many nanometres (nm) are contained in one single micrometre (µm)?", a:"One micrometre contains 1000 nanometres.", difficulty:"medium" },
    { q:"Why is glycerin applied to a specimen before placing the cover slip?", a:"Glycerin is used to keep the specimen moist and prevent it from drying out.", difficulty:"easy" },
    { q:"Identify the specific part of the microscope used for fine-tuning the clarity of the image.", a:"The fine adjustment knob is used for this purpose.", difficulty:"easy" },
    { q:'What defines the "limit of resolution" for the human eye?', a:"It is the minimum distance (0.1 mm) at which two points can be seen as separate.", difficulty:"medium" },
    { q:"Describe the orientation of the hydrophobic tails in the plasma membrane.", a:"The hydrophobic tails point inward, away from the watery environment.", difficulty:"easy" },
    { q:"What is the biological term for a cell that has lost water and its contents have shrunk?", a:'Such a cell is described as being in a "plasmolysed" or "flaccid" state.', difficulty:"easy" },
    { q:"Why does a plant cell not burst when placed in a hypotonic medium?", a:"The rigid cell wall exerts counter-pressure against the swelling cell, preventing it from bursting.", difficulty:"medium" },
    { q:'Name the scientist who first observed "cells" in a thin slice of cork.', a:"Robert Hooke observed them in 1665.", difficulty:"easy" },
    { q:"What is the primary role of integral proteins in the cell membrane?", a:"They act as channels or pumps to transport large or charged molecules across the bilayer.", difficulty:"medium" },
    { q:"Which stain is commonly used to observe animal cells like human cheek cells?", a:"Methylene blue is the stain typically used for cheek cells.", difficulty:"easy" },
    { q:'Define the term "concentration gradient" in relation to cellular transport.', a:"It is the difference in the amount of a substance between the inside and outside of a cell.", difficulty:"easy" },
    { q:"What provides mechanical strength and structural support to a stationary plant?", a:"The rigid cell wall made of cellulose provides this strength.", difficulty:"easy" },
    { q:"Identify the process by which CO2 is excreted from a cell into the environment.", a:"CO2 is excreted through the process of diffusion.", difficulty:"easy" },
    { q:'Why is the cell wall described as "non-living"?', a:"It is a rigid, secreted layer that does not perform active metabolic functions like the membrane.", difficulty:"medium" },
    { q:"What happens to the weight of a carrot when kept in plain water for several hours?", a:"The weight of the carrot increases because it absorbs water by osmosis.", difficulty:"medium" },
    { q:'Which specific model explains the "mosaic" arrangement of proteins in the membrane?', a:"The Fluid-Mosaic Model proposed by Singer and Nicolson.", difficulty:"easy" },
    { q:"What is the thickness of the plasma membrane in nanometres?", a:"The plasma membrane is approximately 7 to 10 nanometres thick.", difficulty:"easy" },
    { q:"In an isotonic solution, what is the net movement of water?", a:"There is no net movement of water, as the concentration is equal on both sides.", difficulty:"easy" },
    { q:'What is the function of the "stage" in a light microscope?', a:"The stage is the platform where the glass slide containing the specimen is placed for observation.", difficulty:"easy" },
    { q:"Why do cells in a boiled Rhoeo leaf fail to show plasmolysis?", a:"Boiling kills the cells, making the membrane fully permeable and unable to regulate osmosis.", difficulty:"hard" }
  ]
};

// Organelle Match game pairs
const MEMORY_PAIRS = [
  ["Plasma membrane", "Controls what enters and leaves the cell"],
  ["Cell wall", "Rigid layer giving plant cells shape and support"],
  ["Nucleus", "Houses the cell's genetic material"],
  ["Mitochondria", "Site of cellular respiration; makes energy"],
  ["Vacuole", "Large sac storing water, keeps the cell turgid"],
  ["Chloroplast", "Site of photosynthesis in plant cells"],
  ["Cytoplasm", "Jelly-like fluid where organelles float"],
  ["Ribosome", "Builds proteins from amino acids"]
];

const GAME_TERMS = {
  terms: [
    { term: 'Plasma membrane', def: 'Thin selectively permeable boundary controlling what enters and leaves the cell.', category: 'Membrane' },
    { term: 'Fluid-mosaic model', def: 'The membrane model describing phospholipids as a fluid layer with proteins scattered through it.', category: 'Membrane' },
    { term: 'Phospholipid bilayer', def: 'Two layers of phospholipids with hydrophilic heads facing water and hydrophobic tails facing inward.', category: 'Membrane' },
    { term: 'Membrane protein', def: 'A protein that helps transport substances, receive signals, or anchor the membrane.', category: 'Membrane' },
    { term: 'Selective permeability', def: 'The property of allowing some substances to cross more easily than others.', category: 'Membrane' },
    { term: 'Diffusion', def: 'Net movement of particles from higher concentration to lower concentration.', category: 'Transport' },
    { term: 'Osmosis', def: 'Diffusion of water through a selectively permeable membrane.', category: 'Transport' },
    { term: 'Active transport', def: 'Movement from low to high concentration using energy, usually ATP.', category: 'Transport' },
    { term: 'Passive transport', def: 'Movement across a membrane without energy input.', category: 'Transport' },
    { term: 'Concentration gradient', def: 'A difference in concentration between two regions.', category: 'Transport' },
    { term: 'Hypotonic solution', def: 'A solution with lower solute concentration than the cell; water tends to enter the cell.', category: 'Transport' },
    { term: 'Hypertonic solution', def: 'A solution with higher solute concentration than the cell; water tends to leave the cell.', category: 'Transport' },
    { term: 'Isotonic solution', def: 'A solution with the same solute concentration as the cell; no net water movement.', category: 'Transport' },
    { term: 'Plasmolysis', def: 'Shrinkage of the cell contents away from the cell wall after water loss in a hypertonic solution.', category: 'Cell wall' },
    { term: 'Turgor pressure', def: 'Water pressure pushing the cell membrane against the cell wall in plant cells.', category: 'Cell wall' },
    { term: 'Cell wall', def: 'Rigid outer layer in plant cells made mainly of cellulose.', category: 'Cell wall' },
    { term: 'Cellulose', def: 'Structural polysaccharide that strengthens plant cell walls.', category: 'Cell wall' },
    { term: 'Nucleus', def: 'Organelle that contains genetic material in eukaryotic cells.', category: 'Organelle' },
    { term: 'Vacuole', def: 'Large storage sac that helps maintain turgidity in plant cells.', category: 'Organelle' },
    { term: 'Ribosome', def: 'Site of protein synthesis.', category: 'Organelle' }
  ],
  tfStatements: [
    { text: 'The plasma membrane is about 7–10 nm thick.', answer: true, why: 'That is the usual textbook thickness of the fluid-mosaic membrane.' },
    { text: 'Hydrophobic heads of phospholipids face the watery environment.', answer: false, why: 'The hydrophilic heads face water; the hydrophobic tails point inward.' },
    { text: 'Diffusion requires ATP.', answer: false, why: 'Diffusion is passive and does not require cellular energy.' },
    { text: 'Osmosis is the movement of water across a selectively permeable membrane.', answer: true, why: 'That is the standard definition of osmosis.' },
    { text: 'Active transport moves substances down the concentration gradient.', answer: false, why: 'Active transport moves substances against the gradient.' },
    { text: 'A hypotonic solution can make a plant cell turgid.', answer: true, why: 'Water enters the plant cell and the vacuole swells, increasing turgor pressure.' },
    { text: 'A hypertonic solution can cause plasmolysis in plant cells.', answer: true, why: 'Water leaves the cell and the membrane pulls away from the wall.' },
    { text: 'The cell wall is selectively permeable like the plasma membrane.', answer: false, why: 'The cell wall is freely permeable; selective permeability is a membrane property.' },
    { text: 'Animal cells have a cell wall.', answer: false, why: 'Animal cells have a plasma membrane but no cell wall.' },
    { text: 'Ribosomes make proteins.', answer: true, why: 'Ribosomes are the site of protein synthesis.' },
    { text: 'The nucleus is the control centre of the cell.', answer: true, why: 'It contains DNA and helps control cell activities.' },
    { text: 'Eukaryotic cells have membrane-bound organelles.', answer: true, why: 'Plant and animal cells have organelles such as the nucleus and mitochondria.' },
    { text: 'Prokaryotes have a true nucleus.', answer: false, why: 'Prokaryotes do not have a membrane-bound nucleus.' },
    { text: 'Water moves into a cell in a hypertonic solution.', answer: false, why: 'Water tends to leave the cell in a hypertonic solution.' },
    { text: 'The plant cell wall is mainly made of cellulose.', answer: true, why: 'Cellulose is the main structural material of plant walls.' },
    { text: 'The fluid part of the fluid-mosaic model allows sideways movement of phospholipids.', answer: true, why: 'Phospholipids and some proteins can move laterally within the membrane.' },
    { text: 'Endocytosis is a type of transport that brings substances into the cell.', answer: true, why: 'The membrane folds inward to form a vesicle.' },
    { text: 'Exocytosis exports substances out of the cell.', answer: true, why: 'Vesicles fuse with the membrane and release their contents outside.' },
    { text: 'A concentration gradient means a difference in concentration between two areas.', answer: true, why: 'Transport processes often depend on this difference.' },
    { text: 'Isotonic means water moves only into the cell.', answer: false, why: 'Water moves both in and out, with no net movement.' },
    { text: 'Membrane proteins can help transport materials.', answer: true, why: 'Channel and carrier proteins assist movement across the membrane.' },
    { text: 'The cell wall gives plant cells support and shape.', answer: true, why: 'Its rigid cellulose structure helps maintain shape.' },
    { text: 'Osmosis is the movement of solute particles.', answer: false, why: 'Osmosis refers specifically to water molecules.' },
    { text: 'Turgor pressure helps keep plant cells firm.', answer: true, why: 'Water pressure inside the cell pushes the membrane against the wall.' }
  ],
  oddGroups: [
    { items: ['Osmosis', 'Diffusion', 'Active transport', 'Ribosome'], odd: 3, why: 'Ribosome is an organelle; the others are transport processes.' },
    { items: ['Cellulose', 'Starch', 'Protein', 'Phospholipid'], odd: 1, why: 'Starch is a storage polysaccharide; the others are structural membrane or wall components.' },
    { items: ['Nucleus', 'Mitochondrion', 'Ribosome', 'Cell wall'], odd: 3, why: 'Cell wall is not an organelle and is outside the membrane.' },
    { items: ['Hypotonic', 'Hypertonic', 'Isotonic', 'Mitochondrial'], odd: 3, why: 'The first three describe solution types; mitochondrial does not.' },
    { items: ['Turgid', 'Plasmolysed', 'Shrivelled', 'Photosynthetic'], odd: 3, why: 'The first three describe cell water states; photosynthetic is a process.' },
    { items: ['Plasma membrane', 'Cell wall', 'Vacuole', 'Chloroplast'], odd: 1, why: 'The cell wall is an outer boundary; the others are organelles or structures inside the cell.' },
    { items: ['Channel protein', 'Carrier protein', 'Enzyme', 'Membrane protein'], odd: 2, why: 'Enzyme is a broad protein type; the others are membrane-transport related.' },
    { items: ['Passive transport', 'Diffusion', 'Osmosis', 'Active transport'], odd: 3, why: 'Active transport uses energy; the others are passive processes.' },
    { items: ['Bacteria', 'Animal cell', 'Plant cell', 'Eukaryote'], odd: 0, why: 'Bacteria are prokaryotes; the others are eukaryotic categories or examples.' },
    { items: ['Cellulose', 'Hydrophobic tails', 'Hydrophilic heads', 'Phospholipid'], odd: 0, why: 'Cellulose is wall material, not a membrane phospholipid part.' },
    { items: ['Endocytosis', 'Exocytosis', 'Osmosis', 'Vesicle'], odd: 2, why: 'Osmosis is water transport, not vesicle transport.' },
    { items: ['Cytoplasm', 'Vacuole', 'Nucleus', 'Membrane'], odd: 3, why: 'Membrane is a boundary, while the others are cell components or organelles.' }
  ],
  cloze: [
    { sentence: 'The plasma membrane follows the ____ model.', answer: 'fluid-mosaic', options: ['fluid-mosaic', 'double-helix', 'lock-and-key', 'cellulose-web'] },
    { sentence: 'Water moving across a selectively permeable membrane is called ____.', answer: 'osmosis', options: ['osmosis', 'diffusion', 'phagocytosis', 'transpiration'] },
    { sentence: 'A solution with lower solute concentration than the cell is ____.', answer: 'hypotonic', options: ['hypotonic', 'hypertonic', 'isotonic', 'neutral'] },
    { sentence: 'A plant cell in a hypertonic solution may undergo ____.', answer: 'plasmolysis', options: ['plasmolysis', 'mitosis', 'lysis', 'turgor'] },
    { sentence: 'The plant cell wall is made mainly of ____.', answer: 'cellulose', options: ['cellulose', 'starch', 'protein', 'lipid'] },
    { sentence: 'Movement from low concentration to high concentration requires ____ transport.', answer: 'active', options: ['active', 'passive', 'simple', 'facilitated'] },
    { sentence: 'A cell that is swollen and firm is described as ____.', answer: 'turgid', options: ['turgid', 'flaccid', 'crenated', 'fragile'] },
    { sentence: 'The cell organelle that contains DNA is the ____.', answer: 'nucleus', options: ['nucleus', 'ribosome', 'vacuole', 'Golgi apparatus'] },
    { sentence: 'Protein synthesis happens on the ____.', answer: 'ribosome', options: ['ribosome', 'lysosome', 'centriole', 'chloroplast'] },
    { sentence: 'The membrane is ____ to many substances.', answer: 'selectively permeable', options: ['selectively permeable', 'opaque', 'rigid', 'electrified'] },
    { sentence: 'The difference in concentration between two areas is the concentration _____.', answer: 'gradient', options: ['gradient', 'equator', 'ratio', 'zone'] },
    { sentence: 'Plant cells take in water and become ____ in hypotonic solutions.', answer: 'turgid', options: ['turgid', 'plasmolysed', 'shrivelled', 'stale'] },
    { sentence: 'Exocytosis moves materials ____ the cell.', answer: 'out of', options: ['out of', 'into', 'around', 'under'] },
    { sentence: 'The fluid part of the membrane allows ____ movement of phospholipids.', answer: 'sideways', options: ['sideways', 'vertical', 'circular', 'random jumping'] },
    { sentence: 'A prokaryote does not have a true ____.', answer: 'nucleus', options: ['nucleus', 'cell wall', 'ribosome', 'membrane'] }
  ],
  searchWords: ['OSMOSIS', 'DIFFUSION', 'MEMBRANE', 'VACUOLE', 'NUCLEUS', 'PROTEIN', 'LIPID', 'TURGOR', 'CELLULOSE', 'RIBOSOME', 'CYTOPLASM', 'PLASMOLYSIS']
};

// Achievement badges — unlocked via app.js, persisted in localStorage
const BADGES = [
  { id: 'first_steps',   label: 'First Steps',     desc: 'Opened your first question set',              icon: '🌱' },
  { id: 'set1_complete', label: 'Set 1 Explorer',  desc: 'Revealed every answer in Set 1',               icon: '🧬' },
  { id: 'set2_complete', label: 'Set 2 Explorer',  desc: 'Revealed every answer in Set 2',               icon: '🔬' },
  { id: 'memory_master', label: 'Memory Master',   desc: 'Cleared Organelle Match in 10 moves or fewer', icon: '🧠' },
  { id: 'perfect_quiz',  label: 'Perfectionist',   desc: 'Scored a perfect run on the Speed Quiz',       icon: '🎯' },
  { id: 'boss_slayer',   label: 'Boss Slayer',     desc: 'Completed Boss Mode',                          icon: '👑' },
  { id: 'streak_10',     label: 'On Fire',         desc: 'Hit a 10-question correct streak',             icon: '🔥' },
  { id: 'level_5',       label: 'Rising Scholar',  desc: 'Reached Level 5',                              icon: '⭐' },
  { id: 'flash_streak',  label: 'Flashcard Fan',   desc: 'Marked "Got it" on 15 flashcards',              icon: '🗂' },
  { id: 'microscopist',  label: 'Microscopist',    desc: 'Brought 5 specimens into perfect focus',       icon: '🔭' },
  { id: 'millionaire_win', label: 'Millionaire',    desc: 'Cleared the full Millionaire Ladder',          icon: '🏆' },
  { id: 'wordsearch_clear', label: 'Word Hunter',   desc: 'Found every word in the Word Search',          icon: '🔎' },
  { id: 'osmosis_ace',    label: 'Osmosis Ace',     desc: 'Solved the Cell Osmosis Lab perfectly',        icon: '💧' },
  { id: 'blitz_20',       label: 'Blitz 20',        desc: 'Scored 20 or more in True/False Blitz',        icon: '⚡' },
  { id: 'chem_explorer',  label: 'Mad Scientist',   desc: 'Discovered 12+ reactions in the Virtual Chemist', icon: '⚗️' }
];


// ===================== Prokaryotic vs Eukaryotic quick-reference table =====================
const PROK_EUK_TABLE = [
  { feature:"Nucleus",            prokaryotic:"Absent — DNA floats free in the cytoplasm", eukaryotic:"Present — DNA enclosed in a nuclear membrane" },
  { feature:"Cell size",          prokaryotic:"Typically 1–10 µm",                          eukaryotic:"Typically 10–100 µm" },
  { feature:"Cell wall",          prokaryotic:"Usually present (peptidoglycan)",            eukaryotic:"Present in plants/fungi (cellulose/chitin), absent in animals" },
  { feature:"Organelles",         prokaryotic:"No membrane-bound organelles",               eukaryotic:"Membrane-bound organelles (mitochondria, ER, Golgi, etc.)" },
  { feature:"Ribosomes",          prokaryotic:"Smaller (70S)",                              eukaryotic:"Larger (80S)" },
  { feature:"DNA structure",      prokaryotic:"Single circular chromosome",                 eukaryotic:"Multiple linear chromosomes" },
  { feature:"Reproduction",       prokaryotic:"Binary fission",                             eukaryotic:"Mitosis / meiosis" },
  { feature:"Examples",           prokaryotic:"Bacteria, archaea",                          eukaryotic:"Plants, animals, fungi, protists" }
];

// ===================== Virtual Microscope: 50 specimens =====================
// No real photos are used (avoids copyright issues and any need for network
// access) — app.js procedurally draws each specimen on an SVG using its
// `shape`/`palette`/`organelles`, and the user must use the coarse/fine focus
// knobs to bring a randomized "true focus" point into view, just like a real scope.
const MICROSCOPE_SPECIMENS = [
  { id:1,  name:"Onion peel epidermis",         category:"Plant",         shape:"hexpack",    palette:["#3a6b3f","#7fd97f"], hasWall:true,  hasNucleus:true,  organelles:[{type:'dot',minTier:1}],                          fact:"Thin, brick-like plant cells with clearly visible cell walls." },
  { id:2,  name:"Rhoeo leaf peel",               category:"Plant",         shape:"hexpack",    palette:["#5a2a5e","#c77dd1"], hasWall:true,  hasNucleus:true,  organelles:[{type:'vacuole',minTier:0}],                       fact:"Purple-pigmented epidermal cells, classic for plasmolysis demos." },
  { id:3,  name:"Elodea leaf",                   category:"Plant",         shape:"hexpack",    palette:["#1f5c2e","#54c46a"], hasWall:true,  hasNucleus:true,  organelles:[{type:'chloroplast',minTier:0},{type:'chloroplast',minTier:1}], fact:"Aquatic plant leaf cells with visible chloroplasts." },
  { id:4,  name:"Potato starch grains",          category:"Plant",         shape:"oval",       palette:["#caa15a","#f0d9a0"], hasWall:false, hasNucleus:false, organelles:[{type:'ring',minTier:1}],                          fact:"Layered, egg-shaped starch grains inside potato cells." },
  { id:5,  name:"Onion root tip (mitosis)",      category:"Plant",         shape:"hexpack",    palette:["#3a6b3f","#9be39b"], hasWall:true,  hasNucleus:true,  organelles:[{type:'dot',minTier:2}],                           fact:"Actively dividing cells showing different mitotic stages." },
  { id:6,  name:"Maize stem cross-section",      category:"Plant",         shape:"rectangle",  palette:["#7a5a2a","#e0b873"], hasWall:true,  hasNucleus:false, organelles:[{type:'ring',minTier:0},{type:'ring',minTier:1}], fact:"Scattered vascular bundles typical of a monocot stem." },
  { id:7,  name:"Dicot leaf cross-section",      category:"Plant",         shape:"rectangle",  palette:["#235c28","#7fd97f"], hasWall:true,  hasNucleus:false, organelles:[{type:'chloroplast',minTier:0}],                   fact:"Layered mesophyll tissue between upper and lower epidermis." },
  { id:8,  name:"Pollen grain",                  category:"Plant",         shape:"star",       palette:["#caa12a","#f7df7a"], hasWall:true,  hasNucleus:true,  organelles:[],                                                 fact:"Spiky-walled grain carrying a plant's genetic material." },
  { id:9,  name:"Moss leaf",                     category:"Plant",         shape:"hexpack",    palette:["#2e6b3a","#7fe08c"], hasWall:true,  hasNucleus:true,  organelles:[{type:'chloroplast',minTier:0}],                   fact:"A single layer of simple photosynthetic cells." },
  { id:10, name:"Spirogyra filament",            category:"Plant",         shape:"tube",       palette:["#1f7a4a","#5be39a"], hasWall:true,  hasNucleus:false, organelles:[{type:'ring',minTier:0}],                          fact:"Algal filament with a spiral chloroplast ribbon." },
  { id:11, name:"Human cheek cell",              category:"Animal",        shape:"irregular",  palette:["#caa6c9","#7d4f7a"], hasWall:false, hasNucleus:true,  organelles:[],                                                 fact:"Flat, irregular epithelial cells from the inner cheek." },
  { id:12, name:"Human blood smear",             category:"Animal",        shape:"round",      palette:["#a32d3a","#e06070"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Disc-shaped red blood cells with no nucleus." },
  { id:13, name:"Frog blood smear",              category:"Animal",        shape:"oval",       palette:["#a32d3a","#e06070"], hasWall:false, hasNucleus:true,  organelles:[],                                                 fact:"Oval, nucleated red blood cells — unlike mammal blood." },
  { id:14, name:"Skeletal muscle fiber",         category:"Animal",        shape:"stripedrod", palette:["#8a3b3b","#d97a7a"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Long fibers with visible banding (striations)." },
  { id:15, name:"Smooth muscle tissue",          category:"Animal",        shape:"irregular",  palette:["#8a4b3b","#d9967a"], hasWall:false, hasNucleus:true,  organelles:[],                                                 fact:"Spindle-shaped cells without visible striations." },
  { id:16, name:"Nerve cell (neuron)",           category:"Animal",        shape:"star",       palette:["#2a4f8a","#7aa6e0"], hasWall:false, hasNucleus:true,  organelles:[],                                                 fact:"Star-shaped body with long thread-like extensions." },
  { id:17, name:"Sperm cells",                   category:"Animal",        shape:"tube",       palette:["#3a5e8a","#7ab0e0"], hasWall:false, hasNucleus:true,  organelles:[],                                                 fact:"Small oval heads, each trailing a single long tail." },
  { id:18, name:"Adipose tissue",                category:"Animal",        shape:"hexpack",    palette:["#caa15a","#f3dba0"], hasWall:false, hasNucleus:true,  organelles:[{type:'vacuole',minTier:0}],                       fact:"Large rounded fat-storage cells packed tightly together." },
  { id:19, name:"Cartilage tissue",              category:"Animal",        shape:"irregular",  palette:["#7a8aa0","#c4d3e6"], hasWall:false, hasNucleus:true,  organelles:[{type:'dot',minTier:1}],                           fact:"Cells sitting in small clusters within a firm matrix." },
  { id:20, name:"Bone tissue cross-section",     category:"Animal",        shape:"round",      palette:["#9a8a6a","#e0d3a8"], hasWall:false, hasNucleus:false, organelles:[{type:'ring',minTier:0},{type:'ring',minTier:1}], fact:"Concentric rings of matrix around tiny central canals." },
  { id:21, name:"Amoeba",                        category:"Microorganism", shape:"irregular",  palette:["#4a6b4a","#9ad19a"], hasWall:false, hasNucleus:true,  organelles:[{type:'vacuole',minTier:0}],                       fact:"Shapeless single cell extending finger-like pseudopodia." },
  { id:22, name:"Paramecium",                    category:"Microorganism", shape:"oval",       palette:["#3a7a7a","#7ad1d1"], hasWall:false, hasNucleus:true,  organelles:[{type:'cilia',minTier:0},{type:'vacuole',minTier:1}], fact:"Slipper-shaped cell covered in fine beating cilia." },
  { id:23, name:"Euglena",                       category:"Microorganism", shape:"oval",       palette:["#2a6b4a","#6ad19a"], hasWall:false, hasNucleus:true,  organelles:[{type:'dot',minTier:1}],                           fact:"Spindle-shaped cell with a single whip-like flagellum." },
  { id:24, name:"Yeast cells",                   category:"Microorganism", shape:"round",      palette:["#caa15a","#f0d9a0"], hasWall:true,  hasNucleus:true,  organelles:[{type:'bud',minTier:0}],                           fact:"Round cells often seen budding off smaller daughter cells." },
  { id:25, name:"Bacteria (cocci)",              category:"Microorganism", shape:"round",      palette:["#8a2a4a","#d97aa0"], hasWall:true,  hasNucleus:false, organelles:[],                                                 fact:"Tiny round bacterial cells, sometimes in chains or clusters." },
  { id:26, name:"Bacteria (bacilli)",            category:"Microorganism", shape:"rod",        palette:["#8a2a4a","#d97aa0"], hasWall:true,  hasNucleus:false, organelles:[],                                                 fact:"Short rod-shaped bacterial cells." },
  { id:27, name:"Diatom",                        category:"Microorganism", shape:"hexpack",    palette:["#caa12a","#f7df7a"], hasWall:true,  hasNucleus:false, organelles:[],                                                 fact:"Single-celled alga with an ornate glass-like silica shell." },
  { id:28, name:"Volvox colony",                 category:"Microorganism", shape:"round",      palette:["#1f7a4a","#5be39a"], hasWall:true,  hasNucleus:false, organelles:[{type:'dot',minTier:0},{type:'dot',minTier:1}],   fact:"Hollow sphere made of hundreds of tiny linked algal cells." },
  { id:29, name:"Hydra",                         category:"Microorganism", shape:"tube",       palette:["#caa15a","#f0d9a0"], hasWall:false, hasNucleus:false, organelles:[{type:'cilia',minTier:0}],                         fact:"Tube-shaped body with a ring of tentacles at one end." },
  { id:30, name:"Plasmodium (malaria parasite)", category:"Microorganism", shape:"round",      palette:["#a32d3a","#e06070"], hasWall:false, hasNucleus:true,  organelles:[{type:'ring',minTier:0}],                          fact:"Ring-shaped parasite stages seen inside red blood cells." },
  { id:31, name:"Human skin cross-section",      category:"Tissue",        shape:"rectangle",  palette:["#caa6c9","#7d4f7a"], hasWall:false, hasNucleus:true,  organelles:[{type:'dot',minTier:1}],                           fact:"Layered epidermis sitting above the dermis." },
  { id:32, name:"Compound eye of insect",        category:"Tissue",        shape:"hexpack",    palette:["#2a4f8a","#7aa6e0"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Hundreds of tiny hexagonal lens facets packed together." },
  { id:33, name:"Feather barb",                  category:"Tissue",        shape:"stripedrod", palette:["#7a8aa0","#c4d3e6"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Central shaft with fine interlocking side branches." },
  { id:34, name:"Hair shaft",                    category:"Tissue",        shape:"tube",       palette:["#5a4a3a","#a08a6a"], hasWall:false, hasNucleus:false, organelles:[{type:'ring',minTier:1}],                          fact:"Long cylindrical fiber with an overlapping scaled surface." },
  { id:35, name:"Fish scale",                    category:"Tissue",        shape:"round",      palette:["#2a6b8a","#7ad1e0"], hasWall:false, hasNucleus:false, organelles:[{type:'ring',minTier:0},{type:'ring',minTier:1}], fact:"Overlapping growth rings, like tree rings, mark its age." },
  { id:36, name:"Mosquito larva",                category:"Tissue",        shape:"tube",       palette:["#3a5e3a","#7ab07a"], hasWall:false, hasNucleus:false, organelles:[{type:'dot',minTier:0}],                           fact:"Segmented aquatic larva with a distinct head and siphon." },
  { id:37, name:"Water flea (Daphnia)",          category:"Tissue",        shape:"irregular",  palette:["#3a6b6a","#7ad1c4"], hasWall:false, hasNucleus:false, organelles:[{type:'dot',minTier:0}],                           fact:"Small transparent crustacean with a visible beating heart." },
  { id:38, name:"Cork cells (Hooke's slide)",    category:"Tissue",        shape:"hexpack",    palette:["#8a5a3a","#caa06a"], hasWall:true,  hasNucleus:false, organelles:[],                                                 fact:"Tightly packed empty boxes — the first cells ever observed." },
  { id:39, name:"Fungal hyphae",                 category:"Tissue",        shape:"stripedrod", palette:["#caa15a","#f0d9a0"], hasWall:true,  hasNucleus:false, organelles:[],                                                 fact:"Branching thread-like filaments forming a fungal network." },
  { id:40, name:"Lichen cross-section",          category:"Tissue",        shape:"irregular",  palette:["#5a7a3a","#a0caa0"], hasWall:true,  hasNucleus:false, organelles:[{type:'dot',minTier:0},{type:'dot',minTier:1}],   fact:"Algal cells scattered within a mesh of fungal threads." },
  { id:41, name:"Table salt crystals",           category:"Other",         shape:"rectangle",  palette:["#cfd8e6","#ffffff"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Perfect cube-shaped crystals of sodium chloride." },
  { id:42, name:"Sugar crystals",                category:"Other",         shape:"hexpack",    palette:["#e6dccb","#ffffff"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Irregular faceted crystals of sucrose." },
  { id:43, name:"Human fingerprint ridge",       category:"Other",         shape:"stripedrod", palette:["#caa6c9","#7d4f7a"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Parallel looping ridge patterns unique to each person." },
  { id:44, name:"Cotton fiber",                  category:"Other",         shape:"tube",       palette:["#e6e6e6","#ffffff"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Flat, twisted ribbon-like natural plant fiber." },
  { id:45, name:"Synthetic fiber",               category:"Other",         shape:"tube",       palette:["#9ab8d8","#d6e8f7"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Perfectly smooth, uniform man-made filament." },
  { id:46, name:"Pencil graphite",               category:"Other",         shape:"rectangle",  palette:["#3a3a3a","#7a7a7a"], hasWall:false, hasNucleus:false, organelles:[{type:'ring',minTier:1}],                          fact:"Stacked, flaky layers of carbon." },
  { id:47, name:"Printed newspaper dot pattern", category:"Other",         shape:"hexpack",    palette:["#1a1a1a","#c0392b"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Tiny colored ink dots that blend into an image from afar." },
  { id:48, name:"Butterfly wing scale",          category:"Other",         shape:"hexpack",    palette:["#caa12a","#3a6b8a"], hasWall:false, hasNucleus:false, organelles:[],                                                 fact:"Overlapping rows of tiny pigmented scales, like roof tiles." },
  { id:49, name:"Mold (Rhizopus) on bread",      category:"Other",         shape:"stripedrod", palette:["#3a3a3a","#8a8a8a"], hasWall:true,  hasNucleus:false, organelles:[{type:'dot',minTier:1}],                           fact:"Fine cottony threads topped with tiny dark spore capsules." },
  { id:50, name:"Pond water sample",             category:"Other",         shape:"irregular",  palette:["#3a6b6a","#7ad1c4"], hasWall:false, hasNucleus:false, organelles:[{type:'dot',minTier:0},{type:'cilia',minTier:1}], fact:"A mix of algae, protozoa, and debris all in a single drop." }
];

// ===================== Virtual Chemist =====================
// A safe, simulated chemistry bench. No real chemicals, no network — app.js
// renders a beaker and looks up reactions in CHEM_REACTIONS by the exact set of
// reagents present plus the applied condition (mix / stir / heat / furnace).
const CHEM_REAGENTS = [
  // Solids
  { id:'sodium',        name:'Sodium (Na)',            state:'solid',  color:'#c9ccd6', emoji:'🔩' },
  { id:'magnesium',     name:'Magnesium (Mg)',         state:'solid',  color:'#d3d6dd', emoji:'🎗️' },
  { id:'zinc',          name:'Zinc (Zn)',              state:'solid',  color:'#a7adba', emoji:'🔗' },
  { id:'iron',          name:'Iron (Fe)',              state:'solid',  color:'#8a8f99', emoji:'🧲' },
  { id:'copper',        name:'Copper (Cu)',            state:'solid',  color:'#b87333', emoji:'🟤' },
  { id:'calcium',       name:'Calcium (Ca)',           state:'solid',  color:'#dfe2e8', emoji:'⚪' },
  { id:'carbon',        name:'Carbon (C)',             state:'solid',  color:'#2b2b2b', emoji:'⚫' },
  { id:'sulfur',        name:'Sulfur (S)',             state:'solid',  color:'#e7d34a', emoji:'🟡' },
  { id:'salt',          name:'Table salt (NaCl)',      state:'solid',  color:'#f2f2f4', emoji:'🧂' },
  { id:'sugar',         name:'Sugar (sucrose)',        state:'solid',  color:'#f6f0e4', emoji:'🍬' },
  { id:'limestone',     name:'Limestone (CaCO₃)',      state:'solid',  color:'#e0dccb', emoji:'🪨' },
  { id:'bakingSoda',    name:'Baking soda (NaHCO₃)',   state:'solid',  color:'#f4f4f0', emoji:'🥄' },
  // Liquids
  { id:'water',         name:'Water (H₂O)',            state:'liquid', color:'#bfe3f2', emoji:'💧' },
  { id:'hcl',           name:'Hydrochloric acid (HCl)',state:'liquid', color:'#e9f7ff', emoji:'🧪' },
  { id:'sulfuricAcid',  name:'Sulfuric acid (H₂SO₄)',  state:'liquid', color:'#fff7e0', emoji:'🧪' },
  { id:'naoh',          name:'Sodium hydroxide (NaOH)',state:'liquid', color:'#eef0f5', emoji:'🧴' },
  { id:'vinegar',       name:'Vinegar (CH₃COOH)',      state:'liquid', color:'#f3ead0', emoji:'🍶' },
  { id:'ethanol',       name:'Ethanol (C₂H₅OH)',       state:'liquid', color:'#eef6ff', emoji:'🥃' },
  { id:'limewater',     name:'Limewater (Ca(OH)₂)',    state:'liquid', color:'#eef4ee', emoji:'🥛' },
  { id:'copperSulfate', name:'Copper sulfate (CuSO₄)', state:'liquid', color:'#2f7fd1', emoji:'🟦' },
  // Gases
  { id:'oxygen',        name:'Oxygen (O₂)',            state:'gas',    color:'#dff0ff', emoji:'🫧' },
  { id:'hydrogen',      name:'Hydrogen (H₂)',          state:'gas',    color:'#eaf3ff', emoji:'💨' },
  { id:'carbonDioxide', name:'Carbon dioxide (CO₂)',   state:'gas',    color:'#e6efe6', emoji:'🌫️' },
  { id:'chlorine',      name:'Chlorine (Cl₂)',         state:'gas',    color:'#d7f0c9', emoji:'🟢' },
  { id:'ammonia',       name:'Ammonia (NH₃)',          state:'gas',    color:'#eef0ff', emoji:'☁️' }
];

// condition: 'mix' fires on combine/stir; 'heat' needs the burner or furnace;
// 'furnace' needs the furnace. app.js matches the exact reagent set and picks
// the highest condition the current action satisfies.
const CHEM_REACTIONS = [
  { id:'na_water', reagents:['sodium','water'], condition:'mix', title:'Sodium reacts violently with water',
    equation:'2Na + 2H₂O → 2NaOH + H₂↑', color:'#eef0f5', bubbles:true, glow:true, flame:true, danger:true,
    desc:'The sodium fizzes, skates across the surface and can ignite, giving off hydrogen and forming an alkaline sodium hydroxide solution.' },
  { id:'ca_water', reagents:['calcium','water'], condition:'mix', title:'Calcium reacts with water',
    equation:'Ca + 2H₂O → Ca(OH)₂ + H₂↑', color:'#eef4ee', bubbles:true,
    desc:'Steady streams of hydrogen bubbles rise as calcium hydroxide (limewater) forms — gentler than sodium.' },
  { id:'mg_hcl', reagents:['magnesium','hcl'], condition:'mix', title:'Magnesium + hydrochloric acid',
    equation:'Mg + 2HCl → MgCl₂ + H₂↑', color:'#e9f7ff', bubbles:true,
    desc:'Brisk bubbling of hydrogen as the reactive metal dissolves in the acid.' },
  { id:'zn_hcl', reagents:['zinc','hcl'], condition:'mix', title:'Zinc + hydrochloric acid',
    equation:'Zn + 2HCl → ZnCl₂ + H₂↑', color:'#eef7ff', bubbles:true,
    desc:'Zinc dissolves with a steady fizz of hydrogen gas.' },
  { id:'fe_hcl', reagents:['iron','hcl'], condition:'mix', title:'Iron + hydrochloric acid',
    equation:'Fe + 2HCl → FeCl₂ + H₂↑', color:'#dff0e6', bubbles:true,
    desc:'Slow bubbling gives hydrogen and a pale green iron(II) chloride solution.' },
  { id:'mg_h2so4', reagents:['magnesium','sulfuricAcid'], condition:'mix', title:'Magnesium + sulfuric acid',
    equation:'Mg + H₂SO₄ → MgSO₄ + H₂↑', color:'#fff7e0', bubbles:true,
    desc:'Hydrogen fizzes off as magnesium sulfate forms.' },
  { id:'zn_h2so4', reagents:['zinc','sulfuricAcid'], condition:'mix', title:'Zinc + sulfuric acid',
    equation:'Zn + H₂SO₄ → ZnSO₄ + H₂↑', color:'#fff7e0', bubbles:true,
    desc:'Zinc dissolves, releasing hydrogen and forming zinc sulfate.' },
  { id:'cu_hcl', reagents:['copper','hcl'], condition:'mix', title:'Copper + hydrochloric acid — no reaction',
    equation:'Cu + HCl → no reaction', color:'#e9f7ff', bubbles:false,
    desc:'Copper sits below hydrogen in the reactivity series, so it does not react with dilute acid.' },
  { id:'hcl_naoh', reagents:['hcl','naoh'], condition:'mix', title:'Neutralisation: acid + alkali',
    equation:'HCl + NaOH → NaCl + H₂O', color:'#eef2f6', glow:true,
    desc:'A neutralisation reaction — the mixture warms up slightly and produces salt water.' },
  { id:'h2so4_naoh', reagents:['sulfuricAcid','naoh'], condition:'mix', title:'Sulfuric acid + sodium hydroxide',
    equation:'H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O', color:'#eef2f6', glow:true,
    desc:'Neutralisation forming sodium sulfate and water, releasing heat.' },
  { id:'limestone_hcl', reagents:['limestone','hcl'], condition:'mix', title:'Carbonate + acid',
    equation:'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑', color:'#eaf7ff', bubbles:true,
    desc:'Vigorous fizzing of carbon dioxide as the limestone dissolves — the classic carbonate test.' },
  { id:'bicarb_vinegar', reagents:['bakingSoda','vinegar'], condition:'mix', title:'Baking soda + vinegar volcano',
    equation:'NaHCO₃ + CH₃COOH → CH₃COONa + H₂O + CO₂↑', color:'#f1ead2', bubbles:true,
    desc:'A foaming eruption of carbon dioxide — the kitchen-volcano reaction.' },
  { id:'bicarb_hcl', reagents:['bakingSoda','hcl'], condition:'mix', title:'Baking soda + hydrochloric acid',
    equation:'NaHCO₃ + HCl → NaCl + H₂O + CO₂↑', color:'#eaf7ff', bubbles:true,
    desc:'Rapid fizzing releases carbon dioxide.' },
  { id:'co2_limewater', reagents:['carbonDioxide','limewater'], condition:'mix', title:'Carbon dioxide turns limewater milky',
    equation:'CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O', color:'#eef4ee', precipitate:'#ffffff',
    desc:'A white precipitate of calcium carbonate clouds the limewater — the standard test for CO₂.' },
  { id:'zn_cuso4', reagents:['zinc','copperSulfate'], condition:'mix', title:'Zinc displaces copper',
    equation:'Zn + CuSO₄ → ZnSO₄ + Cu', color:'#9fbfd6', precipitate:'#b87333',
    desc:'The blue colour fades as reddish-brown copper is displaced and coats the zinc.' },
  { id:'fe_cuso4', reagents:['iron','copperSulfate'], condition:'mix', title:'Iron displaces copper',
    equation:'Fe + CuSO₄ → FeSO₄ + Cu', color:'#8fb59a', precipitate:'#b87333',
    desc:'A copper coating forms on the iron and the solution turns pale green.' },
  { id:'nh3_hcl', reagents:['ammonia','hcl'], condition:'mix', title:'Ammonia + hydrogen chloride',
    equation:'NH₃ + HCl → NH₄Cl', color:'#eef0ff', smoke:true,
    desc:'Dense white smoke of solid ammonium chloride forms where the two gases meet.' },
  { id:'cl2_water', reagents:['chlorine','water'], condition:'mix', title:'Chlorine dissolves in water',
    equation:'Cl₂ + H₂O → HCl + HOCl', color:'#dff0c9',
    desc:'Pale green chlorine water forms — a bleaching, disinfecting solution.' },
  { id:'salt_water', reagents:['salt','water'], condition:'mix', title:'Salt dissolves in water',
    equation:'NaCl (s) → Na⁺(aq) + Cl⁻(aq)', color:'#dbeaf2',
    desc:'The salt dissolves to give a clear sodium chloride solution — a physical change, not a reaction.' },
  { id:'sugar_water', reagents:['sugar','water'], condition:'mix', title:'Sugar dissolves in water',
    equation:'sucrose (s) → sucrose (aq)', color:'#e7edf0',
    desc:'The sugar dissolves into a clear syrup — a physical change.' },
  { id:'h2so4_water', reagents:['sulfuricAcid','water'], condition:'mix', title:'Diluting sulfuric acid',
    equation:'H₂SO₄ + water → dilute acid (exothermic)', color:'#fdf3d6', glow:true, danger:true,
    desc:'Mixing releases a lot of heat — always add acid to water, never water to acid.' },
  // Heat-driven reactions
  { id:'mg_o2', reagents:['magnesium','oxygen'], condition:'heat', title:'Magnesium burns in oxygen',
    equation:'2Mg + O₂ → 2MgO', color:'#f4f4f4', flame:true, glow:true, danger:true,
    desc:'A blinding white flame leaves a white ash of magnesium oxide.' },
  { id:'cu_o2', reagents:['copper','oxygen'], condition:'heat', title:'Copper oxidises on heating',
    equation:'2Cu + O₂ → 2CuO', color:'#2b2b2b', glow:true,
    desc:'The shiny copper turns black as a layer of copper(II) oxide forms.' },
  { id:'s_o2', reagents:['sulfur','oxygen'], condition:'heat', title:'Sulfur burns in oxygen',
    equation:'S + O₂ → SO₂', color:'#dfe6ea', flame:true,
    desc:'Sulfur burns with a blue flame, giving choking sulfur dioxide gas.' },
  { id:'c_o2', reagents:['carbon','oxygen'], condition:'heat', title:'Carbon burns in oxygen',
    equation:'C + O₂ → CO₂', color:'#3a3a3a', flame:true, glow:true,
    desc:'The carbon glows red-hot and produces carbon dioxide.' },
  { id:'h2_o2', reagents:['hydrogen','oxygen'], condition:'heat', title:'Hydrogen + oxygen — the squeaky pop',
    equation:'2H₂ + O₂ → 2H₂O', color:'#dff0ff', flame:true, danger:true,
    desc:'A small explosion (the "pop" test) forms water vapour.' },
  { id:'fe_s', reagents:['iron','sulfur'], condition:'heat', title:'Iron + sulfur',
    equation:'Fe + S → FeS', color:'#3b2f2f', glow:true,
    desc:'The mixture glows red and forms grey-black iron(II) sulfide, which is no longer magnetic.' },
  { id:'ethanol_o2', reagents:['ethanol','oxygen'], condition:'heat', title:'Ethanol combustion',
    equation:'C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O', color:'#dff0ff', flame:true,
    desc:'Ethanol burns with a clean blue flame, giving carbon dioxide and water.' },
  { id:'sugar_heat', reagents:['sugar'], condition:'heat', title:'Sugar caramelises',
    equation:'sucrose --heat--> caramel', color:'#7a4a1e', glow:true,
    desc:'Gentle heat melts and browns the sugar into caramel.' },
  // Furnace-only (strong heat)
  { id:'sugar_furnace', reagents:['sugar'], condition:'furnace', title:'Sugar chars to carbon',
    equation:'sucrose --strong heat--> C + H₂O↑', color:'#1c1c1c', glow:true, smoke:true,
    desc:'In the furnace the sugar blackens to a lump of carbon, driving off steam.' },
  { id:'limestone_furnace', reagents:['limestone'], condition:'furnace', title:'Thermal decomposition of limestone',
    equation:'CaCO₃ --strong heat--> CaO + CO₂↑', color:'#efeae0', glow:true,
    desc:'Strong heating breaks limestone into quicklime (calcium oxide) and carbon dioxide.' },
  { id:'zn_o2_furnace', reagents:['zinc','oxygen'], condition:'furnace', title:'Zinc burns to zinc oxide',
    equation:'2Zn + O₂ → 2ZnO', color:'#f1f1ee', glow:true,
    desc:'Zinc burns to zinc oxide — yellow while hot, white when cool.' }
];
